FROM apache/airflow:2.9.1-python3.12

USER root

RUN apt-get update && \
    apt-get install -y default-jre procps && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/default-java

USER airflow

RUN pip install --no-cache-dir \
    boto3 \
    requests \
    pyspark==3.5.1 \
    great_expectations \
    pyarrow