services:
  postgres:
    image: postgres:15
    container_name: logistics_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: data_warehouse
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - data_network

  minio:
    image: minio/minio
    container_name: logistics_minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - data_network
      - logistics_net

  api-mock:
    build: ./api-mock
    container_name: logistics_api
    ports:
      - "8000:8000"
    networks:
      - data_network

  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: logistics_airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/data_warehouse
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
      - SPARK_MINIO_USER=${SPARK_MINIO_USER}
      - SPARK_MINIO_PASSWORD=${SPARK_MINIO_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./jobs:/opt/airflow/jobs
    command: >
      bash -c "pip install boto3 requests &&
      airflow db migrate &&
      airflow users create --username ${AIRFLOW_USER} --password ${AIRFLOW_PASSWORD} --firstname Admin --lastname User --role Admin --email admin@example.com &&
      airflow webserver -p 8080 -D &&
      airflow scheduler"
    networks:
      - data_network
    depends_on:
      postgres:
        condition: service_started
      minio:
        condition: service_started
      api-mock:
        condition: service_started

  analytics-api:
    build: ./analytics-api
    container_name: logistics_analytics_api
    ports:
      - "8001:8001"
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
    depends_on:
      - minio
    networks:
      - logistics_net

volumes:
  pg_data:
  minio_data:

networks:
  data_network:
    driver: bridge
  logistics_net:
    driver: bridge