name: 'smart_logistics'
version: '1.0.0'
config-version: 2

profile: 'logistics_pg'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  smart_logistics:
    staging:
      +materialized: view
    marts:
      +materialized: table

# Trigger CI/CD pipeline