logistics_pg:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      port: 5432
      dbname: gold_db
      schema: public
      threads: 4